version: "3.4"

services:
  frontend:
    image: adfinissygroup/dinacon-awards-frontend
    build:
      context: .
      cache_from:
        - danlynn/ember-cli
        - nginx
        - adfinissygroup/dinacon-awards-frontend
    depends_on:
      - caluma
      - keycloak
    ports:
      - "80:80"

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=dinacon_awards
    volumes:
      - dbdata:/var/lib/postgresql/data

  caluma:
    image: adfinis-sygroup/dinacon-awards-caluma
    build:
      context: caluma
      cache_from:
        - projectcaluma/caluma
        - adfinissygroup/dinacon-awards-caluma
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=dinacon_awards
      - DATABASE_USER=dinacon_awards
    depends_on:
      - db
      - minio
      - keycloak

  keycloak:
    image: jboss/keycloak:9.0.3
    depends_on:
      - db
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=dinacon_awards
      - DB_DATABASE=dinacon_awards
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data

volumes:
  dbdata:
  minio_data:
